In [24]:
import numpy as np

In [27]:
vectors = np.array([[0.130746, 0.309203, 0.457567, 0.645221],
                            [0.0178319, 0.448561, 0.479029, 0.860906],
                            [-0.901462, 0.0169294, 0.440464, 0.0684007],
                            [-0.0240213, 0.454003, 0.207199, 0.498046]])

word_list = ["the", "and", "of", "to"]

def l2_dist(word1_vector, word2_vector):
    return np.sum(np.sqrt(np.square(word1_vector - word2_vector)))

In [30]:
word1 = "the"
word2 = "to"

word1_vector = vectors[word_list.index(word1)]
word2_vector = vectors[word_list.index(word2)]
l2_distance = l2_dist(word1_vector, word2_vector)

print(word1_vector)
print(word2_vector)
print((word1_vector - word2_vector))
print(l2_distance)



[ 0.130746  0.309203  0.457567  0.645221]
[-0.0240213  0.454003   0.207199   0.498046 ]
[ 0.1547673 -0.1448     0.250368   0.147175 ]
0.6971103


In [31]:
print(vectors)

[[ 0.130746   0.309203   0.457567   0.645221 ]
 [ 0.0178319  0.448561   0.479029   0.860906 ]
 [-0.901462   0.0169294  0.440464   0.0684007]
 [-0.0240213  0.454003   0.207199   0.498046 ]]


In [32]:
print(vectors[0][0])

0.130746


In [33]:
vectors[0][0] = 1.0
print(vectors[0][0])

1.0


In [48]:
input = np.zeros((1,10), dtype=np.float64)
input

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [49]:
input += np.array([1,3,2,4,6,5,8,7,10,9])
input

array([[  1.,   3.,   2.,   4.,   6.,   5.,   8.,   7.,  10.,   9.]])

In [50]:
input += np.array([0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,0.10])
input

array([[  1.1,   3.2,   2.3,   4.4,   6.5,   5.6,   8.7,   7.8,  10.9,
          9.1]])

In [52]:
np.argsort(input, reverse)


NameError: name 'reverse' is not defined

NameError: name 'argsort' is not defined