In [16]:
import numpy as np

In [18]:
vectors = np.array([[0.130746, 0.309203, 0.457567, 0.645221],
                            [0.0178319, 0.448561, 0.479029, 0.860906],
                            [-0.901462, 0.0169294, 0.440464, 0.0684007],
                            [-0.0240213, 0.454003, 0.207199, 0.498046]])
word_list = ["the", "and", "of", "to"]

print(vectors)
print(vectors[0])

print(word_list)

print(word_list[0])

[[ 0.130746   0.309203   0.457567   0.645221 ]
 [ 0.0178319  0.448561   0.479029   0.860906 ]
 [-0.901462   0.0169294  0.440464   0.0684007]
 [-0.0240213  0.454003   0.207199   0.498046 ]]
[ 0.130746  0.309203  0.457567  0.645221]
['the', 'and', 'of', 'to']
the


In [23]:
word1 = 'the'
word1_idx = word_list.index(word1)
print(word1_idx)
print(vectors[word1_idx])

0
[ 0.130746  0.309203  0.457567  0.645221]
