In [24]:
import numpy as np

In [27]:
vectors = np.array([[0.130746, 0.309203, 0.457567, 0.645221],
                            [0.0178319, 0.448561, 0.479029, 0.860906],
                            [-0.901462, 0.0169294, 0.440464, 0.0684007],
                            [-0.0240213, 0.454003, 0.207199, 0.498046]])

word_list = ["the", "and", "of", "to"]

def l2_dist(word1_vector, word2_vector):
    return np.sum(np.sqrt(np.square(word1_vector - word2_vector)))

In [30]:
word1 = "the"
word2 = "to"

word1_vector = vectors[word_list.index(word1)]
word2_vector = vectors[word_list.index(word2)]
l2_distance = l2_dist(word1_vector, word2_vector)

print(word1_vector)
print(word2_vector)
print((word1_vector - word2_vector))
print(l2_distance)



[ 0.130746  0.309203  0.457567  0.645221]
[-0.0240213  0.454003   0.207199   0.498046 ]
[ 0.1547673 -0.1448     0.250368   0.147175 ]
0.6971103


In [31]:
print(vectors)

[[ 0.130746   0.309203   0.457567   0.645221 ]
 [ 0.0178319  0.448561   0.479029   0.860906 ]
 [-0.901462   0.0169294  0.440464   0.0684007]
 [-0.0240213  0.454003   0.207199   0.498046 ]]


In [32]:
print(vectors[0][0])

0.130746


In [33]:
vectors[0][0] = 1.0
print(vectors[0][0])

1.0


In [68]:
a = np.array([1,2,3])
b = np.array([-1,-4,-5])


In [69]:
np.square(a)

array([1, 4, 9])

In [70]:
np.sum(np.square(a))

14

In [71]:
np.sqrt(np.sum(np.square(a)))

3.7416573867739413

In [72]:
np.sqrt(np.sum(np.square(a))) * np.sqrt(np.sum(np.square(b)))

24.248711305964282

In [73]:
np.dot(a,b)

-24

In [76]:
type(np.dot(a,b) / (np.sqrt(np.sum(np.square(a))) * np.sqrt(np.sum(np.square(b)))))

numpy.float64

In [75]:
c = np.array([0 , -1 , 2])
np.argsort(c)

array([1, 0, 2])